---

# Install the necessary config maps

- name: Set up nGinx vhost config
  k8s:
    state: present
    name: openzaak-nginx
    namespace: "{{ openzaak_namespace }}"
    definition: "{{ lookup('template', 'nginx-config.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  register: openzaak_nginx_config


- name: Set up redis config
  k8s:
    state: present
    name: "{{ openzaak_redis_config_name }}"
    namespace: "{{ openzaak_namespace }}"
    definition: "{{ lookup('template', 'redis-config.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
