---

# Set up the required deployments

# TODO: https://rancher.com/blog/2019/deploying-redis-cluster/

- name: Set up Redis cache
  k8s:
    state: present
    name: openzaak-redis
    namespace: "{{ openzaak_namespace }}"
    definition: "{{ lookup('template', 'redis.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes

- name: Set up Open Zaak
  k8s:
    state: present
    name: openzaak
    namespace: "{{ openzaak_namespace }}"
    definition: "{{ lookup('template', 'openzaak.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes

- name: Set up nGinx
  k8s:
    state: present
    name: openzaak-nginx
    namespace: "{{ openzaak_namespace }}"
    definition: "{{ lookup('template', 'nginx.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  vars:
    config_version: "{{ openzaak_nginx_config.result.metadata.resourceVersion }}"
