---

- name: Install Ingress Route
  k8s:
    state: present
    name: openzaak
    namespace: "{{ openzaak_namespace }}"
    definition: "{{ lookup('template', openzaak_ingress_tpl|default('ingress.yml.j2')) | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
