---

- name: Set up the required namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ openzaak_namespace }}"
    validate:
      fail_on_error: yes
      strict: yes
  when: openzaak_manage_namespace
