---

- name: Create the PVC
  k8s:
    state: present
    name: "{{ openzaak_storage_name }}"
    namespace: "{{ openzaak_namespace }}"
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: "{{ openzaak_storage_class_name }}"
        resources:
          requests:
            storage: "{{ openzaak_storage }}"
  when: openzaak_provision_storage
