---

# Set up the TLS secrets

- name: Install TLS secrets
  k8s:
    state: present
    name: openzaak-tls-secrets
    namespace: "{{ openzaak_namespace }}"
    definition: "{{ lookup('template', 'tls.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  no_log: True
