---

# Generate and install the systemd units for the pod/containers
# Reference: http://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html

- name: Get user ID of podman user
  getent:
    database: passwd
    key: "{{ openzaak_podman_user }}"

- name: Systemd unit files for openzaak container must exist
  containers.podman.podman_generate_systemd:
    name: openzaak
    dest: /home/{{ openzaak_podman_user }}/.config/systemd/user
    restart_policy: always
    no_header: true
  become_user: "{{ openzaak_podman_user }}"

# See issue: https://github.com/containers/podman/pull/15777
# If you are using podman version 2.3.1 >= ansible idempotence will leave this alone.
- name: Fix systemd pod services
  ansible.builtin.lineinfile:
    path: /home/{{ openzaak_podman_user }}/.config/systemd/user/pod-openzaak.service
    regexp: '^Requires=$'
    line: 'Wants'
    backrefs: true

- name: Enable linger
  command: loginctl enable-linger {{ openzaak_podman_user }}
  changed_when: false
  become_user: "{{ openzaak_podman_user }}"
  # Reference https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples (last one) and https://access.redhat.com/discussions/6029491
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[openzaak_podman_user][1] }}"

- name: Enable service
  systemd:
    name: pod-openzaak.service
    state: started
    enabled: true
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ openzaak_podman_user }}"
  # Reference https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples (last one) and https://access.redhat.com/discussions/6029491
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[openzaak_podman_user][1] }}"
