---

# Generate and install the systemd units for the pod/containers
# Reference: http://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html

- name: Systemd unit files for openzaak container must exist
  containers.podman.podman_generate_systemd:
    name: openzaak
    dest: /home/{{ openzaak_podman_user }}/.config/systemd/user
    restart_policy: always
  become: true
  become_user: "{{ openzaak_podman_user }}"

- name: Enable linger
  command: loginctl enable-linger
  args:
    creates: "/var/lib/systemd/linger/{{ openzaak_podman_user }}"

- name: Enable service
  systemd:
    name: pod-openzaak.service
    state: started
    enabled: true
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ openzaak_podman_user }}"
