---

- name: Set up the persistent storage
  containers.podman.podman_volume:
    name: openzaak-private-media
  register: openzaak_volume
  notify:
    - print volume mountpoint
  become: true
  become_user: "{{ openzaak_podman_user }}"

- name: Ensure user group can enter container volumes directory
  file:
    path: "{{ item }}"
    state: directory
    mode: g=x
  loop:
    - "/home/{{ openzaak_podman_user }}"
    - "/home/{{ openzaak_podman_user }}/.local"
    - "/home/{{ openzaak_podman_user }}/.local/share"
    - "/home/{{ openzaak_podman_user }}/.local/share/containers"
    - "/home/{{ openzaak_podman_user }}/.local/share/containers/storage"
    - "/home/{{ openzaak_podman_user }}/.local/share/containers/storage/volumes"
    - "/home/{{ openzaak_podman_user }}/.local/share/containers/storage/volumes/openzaak-private-media"
