---

# Install the Traefik ingress route(s)

# HTTP

- name: Install HTTP Ingress Route
  k8s:
    state: present
    name: opennotificaties-http
    namespace: "{{ opennotificaties_namespace }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      spec:
        entryPoints:
          - web
        routes:
        - match: Host(`{{ opennotificaties_domain }}`)
          kind: Rule
          services:
            - name: opennotificaties
              port: 8000
          middlewares:
            - name: https-redirect
              namespace: default

# HTTPS

- name: Install HTTPS Ingress Route
  k8s:
    state: present
    name: opennotificaties-https
    namespace: "{{ opennotificaties_namespace }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      spec:
        entryPoints:
          - websecure
        routes:
        - match: Host(`{{ opennotificaties_domain }}`)
          kind: Rule
          services:
          - name: opennotificaties
            port: 8000
          middlewares:
            - name: https-hsts
              namespace: default
        tls:
          certResolver: default
          options:
            namespace: default
            name: default
