---

# Set up the environment files on the host machine

- name: Create application configuration directory
  file:
    path: /home/{{ opennotificaties_podman_user }}/opennotificaties/
    state: directory
    owner: "{{ opennotificaties_podman_user }}"
    group: "{{ opennotificaties_podman_user }}"

- name: Setup the environment variables
  template:
    src: "{{ opennotificaties_env_template }}"
    dest: /home/{{ opennotificaties_podman_user }}/opennotificaties/.env
    mode: u=rwx,g-rwx,o-rwx
    owner: "{{ opennotificaties_podman_user }}"
    group: "{{ opennotificaties_podman_user }}"
  register: opennotificaties_env_file_template
