---

# Generate and install the systemd units for the pod/containers
# Reference: http://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html

- name: Get user ID of podman user
  getent:
    database: passwd
    key: "{{ opennotificaties_podman_user }}"

- name: Ensure the systemd unit dir exists
  file:
    path: "/home/{{ opennotificaties_podman_user }}/.config/systemd/user"
    state: directory

- name: Template out systemd unit file
  template:
    src: pod.service.j2
    dest: "/home/{{ opennotificaties_podman_user }}/.config/systemd/user/pod-opennotificaties.service"
  vars:
    user_id: "{{ getent_passwd[opennotificaties_podman_user][1] }}"
  register: opennotificaties_systemd_unit

- name: Enable linger
  command: loginctl enable-linger
  args:
    creates: "/var/lib/systemd/linger/{{ opennotificaties_podman_user }}"

- name: Enable service
  systemd:
    name: pod-opennotificaties.service
    state: started
    enabled: yes
    scope: user
    daemon_reload: "{{ opennotificaties_systemd_unit.changed }}"
