---

postgresql_data_dir: "/var/lib/pgsql/{{ postgresql_version }}/data"
postgresql_bin_path: "/usr/pgsql-{{ postgresql_version }}/bin"
postgresql_config_path: "{{ postgresql_data_dir }}"
postgresql_daemon: "postgresql-{{ postgresql_version }}"
postgresql_packages:
  - "postgresql{{ postgresql_version }}"
  - "postgresql{{ postgresql_version }}-server"
  - "postgresql{{ postgresql_version }}-contrib"
  - "postgresql{{ postgresql_version }}-libs"
  - "libpq5-devel"
  - "postgis30_{{ postgresql_version }}"

postgresql_python_library: python-psycopg2
