---

# Template out the certificates
- name: Ensure certs dir exists with correct file permissions
  file:
    path: /home/nlx/certs
    state: directory
    owner: nlx
    group: nlx
    recurse: no
    mode: o=rwx,g=rx,o=rx

- name: Install certificates
  copy:
    dest: "/home/nlx/certs/{{ item.name }}"
    content: "{{ item.content }}"
    owner: nlx
    group: nlx
    mode: o=rw,g=r,o-rwx
  with_items:
    - name: root.crt
      content: "{{ nlx_root_cert }}"
    - name: org.key
      content: "{{ nlx_inway_key }}"
    - name: org.crt
      content: "{{ nlx_inway_cert }}"
  no_log: true
