---

- import_tasks: setup_env.yml

- import_tasks: dependencies.yml
- import_tasks: network.yml
- import_tasks: containers.yml

# load the nginx template
- import_role:
    name: openzaak.deploy.open_notificaties_nginx
