---

# Set up the environment files on the host machine

- name: Create application user
  user:
    name: opennotificaties
    comment: Application user
    create_home: yes
    state: present

- name: Setup the environment variables
  template:
    src: env.j2
    dest: /home/opennotificaties/.env
    mode: 0400
  register: opennotificaties_env_file_template
