---
__postgresql_version: "10"
__postgresql_postgis_repositories:
  - name: Application:Geo
    repo: http://download.opensuse.org/repositories/Application:/Geo/SLE_15_SP1_Backports/
  - name: science
    repo: http://download.opensuse.org/repositories/science/SLE_15_SP1/
