---

- name: restart inway
  docker_container:
    name: "{{ item }}"
    restart: yes
  with_items: "{{ nlx_inway_replicas }}"

- name: restart outway
  docker_container:
    name: "{{ item }}"
    restart: yes
  with_items: "{{ nlx_outway_replicas }}"
