---

- package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - sudo
      - python3-pip

- name: Checking if we have a strong server-specific DH key
  stat:
    path: /etc/ssl/certs/dhparam.pem
  register: has_dhparams

- name: Generating strong server-specific DH key (this may take >10 minutes on first run)
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
  when: has_dhparams.stat.exists == False

- name: Set up postgresql debian repo (apt-key)
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Set up postgresql debian repo (apt-repository)
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
