---

- name: Run the cache service
  docker_container:
    name: cache
    image: redis:5
    pull: yes
    hostname: cache
    restart_policy: always
    networks:
      - name: openzaak
    purge_networks: no
    networks_cli_compatible: yes

- name: Run the Open Zaak backend service
  docker_container:
    name: "{{ item.name }}"
    image: "{{ openzaak_image }}"
    pull: yes
    hostname: "{{ item.name }}"
    restart_policy: always
    state: started
    restart: "{{ openzaak_env_file_template.changed }}"
    networks:
      - name: openzaak
    purge_networks: yes
    networks_cli_compatible: yes
    volumes: "{{ lookup('template', 'volumes.yml.j2') | from_yaml }}"
    ports:
      - "127.0.0.1:{{ item.port }}:8000"
    env:
      DB_HOST: "{{ openzaak_db_host }}"
      DB_PORT: "{{ openzaak_db_port | string }}"
      SECRET_KEY: "{{ openzaak_secret_key }}"
      SUBPATH: "{{ openzaak_subpath }}"
  with_items: "{{ openzaak_replicas }}"
