---

- name: Set up the persistent storage
  docker_volume:
    name: openzaak-private-media
  register: openzaak_volume
  notify:
    - print volume mountpoint

- name: Set volume permissions
  file:
    path: "{{ openzaak_volume.volume.Mountpoint }}"
    state: directory
    owner: openzaak
    group: openzaak
    recurse: no
    mode: u=rwx,g=rx,o-rwx
