---

- name: Run RHEL/CentOS 7 Postgres setup
  import_tasks: repos-7.yml
  when: ansible_distribution_major_version == "7"

- name: Run RHEL/CentOS 8 Postgres setup
  import_tasks: repos-8.yml
  when: ansible_distribution_major_version == "8"
