galaxy_info:
  author: Maykin Media
  description: Set up a Red Hat-based OS for Open Zaak/Open Notificaties installs
  company: Maykin Media

  issue_tracker_url: https://github.com/open-zaak/ansible-collection/issues

  license: EUPL-1.2

  min_ansible_version: '2.9'

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags:
    - provision
    - openzaak
    - commonground

dependencies: []
