---
# Variable configuration.
- name: Include OS-specific variables (OpenSUSE).
  include_vars: "OpenSUSE-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'openSUSE Leap'

- name: Include OS-specific variables (SLES).
  include_vars: "SLES-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution != 'openSUSE Leap'

- name: Define postgresql_geo_repository
  set_fact:
    postgresql_geo_repository: "{{ __postgresql_geo_repository }}"
  when: postgresql_geo_repository is not defined

- name: Define postgresql_version.
  set_fact:
    postgresql_version: "{{ __postgresql_version }}"
  when: postgresql_version is not defined
